version: "3.7"
services:
  config-service:
    hostname: config-service
    image: macoredroid/config-service:latest
    build:
      context: ./config-service
    ports:
      - "8088:8088"
    networks:
      - spring-cloud-network
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"server": {"git" :{"uri": "https://github.com/MaCoredroid/test-config-docker.git"}}}}}}'

  discovery-service:
    hostname: discovery-service
    image: macoredroid/discovery-service:latest
    build:
      context: ./discovery-service
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "30752:30752"
    networks:
      - spring-cloud-network

  pet-service:
    hostname: pet-service
    image: macoredroid/pet-service:latest
    build:
      context: ./pet-service
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8091:8091"
    networks:
      - spring-cloud-network

  user-service:
    hostname: user-service
    image: macoredroid/user-service:latest
    build:
      context: ./user-service
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8092:8092"
    networks:
      - spring-cloud-network

  record-service:
    hostname: record-service
    image: macoredroid/record-service:latest
    build:
      context: ./record-service
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8093:8093"
    networks:
      - spring-cloud-network

  location-service:
    hostname: location-service
    image: macoredroid/location-service:latest
    build:
      context: ./location-service
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8094:8094"
    networks:
      - spring-cloud-network

  proxy-service:
    hostname: proxy-service
    image: macoredroid/proxy-service:latest
    build:
      context: ./proxy-service
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "30751:30751"
    networks:
      - spring-cloud-network

  rule-service:
    hostname: rule-service
    image: macoredroid/rule-service:latest
    build:
      context: ./rule-service
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8095:8095"
    networks:
      - spring-cloud-network
  
  forum-service:
    hostname: forum-service
    image: macoredroid/forum-service:latest
    build:
      context: ./forum-service
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8096:8096"
    networks:
      - spring-cloud-network


networks:
  spring-cloud-network:
    driver: bridge



