version: "3.7"
services:
  config-service:
    image: config-service
    build:
      context: ./config-service
    ports:
      - "8088:8088"
    networks:
      - spring-cloud-network

  discovery-service:
    hostname: discovery-service
    image: discovery-service
    build:
      context: ./discovery-service
    links:
      - "config-service"
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8061:8061"
    networks:
      - spring-cloud-network
      
  pet-service:
    image: pet-service
    build:
      context: ./pet-service
    links:
      - "discovery-service"
      - "config-service"
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8091:8091"
    networks:
      - spring-cloud-network


  user-service:
    image: user-service
    build:
      context: ./user-service
    links:
      - "discovery-service"
      - "config-service"
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8092:8092"
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge

        
 
