version: "3.7"
services:
  config-service:
    image: config-service
    build:
      context: ./config-service
    ports:
      - "8088:8088"
    networks:
      - spring-cloud-network

  mysql-pet:
    hostname: mysql-pet
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=c7o2r1e4
      - MYSQL_DATABASE=pet
      - MYSQL_USER=coredroid
      - MYSQL_PASSWORD=c7o2r1e4
    volumes:
      - /data/mysql/pet
    ports:
      - "3306:3306"
    networks:
      - spring-cloud-network

  mysql-user:
    hostname: mysql-user
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=c7o2r1e4
      - MYSQL_DATABASE=pet
      - MYSQL_USER=coredroid
      - MYSQL_PASSWORD=c7o2r1e4
    volumes:
      - /data/mysql/user
    ports:
      - "3307:3306"
    networks:
      - spring-cloud-network

  discovery-service:
    hostname: discovery-service
    image: discovery-service
    build:
      context: ./discovery-service
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8061:8061"
    networks:
      - spring-cloud-network
  
  pet-service:
    hostname: pet-service
    image: pet-service
    build:
      context: ./pet-service
    depends_on:
      - mysql-pet
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8091:8091"
    networks:
      - spring-cloud-network

  user-service:
    hostname: user-service
    image: user-service
    build:
      context: ./user-service
    depends_on:
      - mysql-user
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8092:8092"
    networks:
      - spring-cloud-network

  gateway-service:
    hostname: gateway-service
    image: gateway-service
    build:
      context: ./gateway-service
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8060:8060"
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge

        
 
