version: "3.7"
services:
  config-service:
    image: config-service
    build:
      context: ./config-service
    ports:
      - "8088:8088"
    networks:
      - spring-cloud-network

  discovery-service:
    hostname: discovery-service
    image: discovery-service
    build:
      context: ./discovery-service
    links:
      - "config-service"
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8061:8061"
    networks:
      - spring-cloud-network
      
  department-service:
    image: department-service
    build:
      context: ./department-service
    links:
      - "discovery-service"
      - "config-service"
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8091:8091"
    networks:
      - spring-cloud-network

  employee-service:
    image: employee-service
    build:
      context: ./employee-service
    links:
      - "discovery-service"
      - "config-service"
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8090:8090"
    networks:
      - spring-cloud-network
      
  gateway-service:
    image: gateway-service
    build:
      context: ./gateway-service
    links:
      - "discovery-service"
      - "config-service"
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8060:8060"
    networks:
      - spring-cloud-network

  organization-service:
    image: organization-service
    build:
      context: ./organization-service
    links:
      - "discovery-service"
      - "config-service"
      - "department-service"
      - "employee-service"
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8092:8092"
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge

        
 
