version: "3.7"
services:
  config-service:
    hostname: config-service
    image: macoredroid/config-service:latest
    ports:
      - "8088:8088"
    networks:
      - spring-cloud-network
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"server": {"git" :{"uri": "https://github.com/MaCoredroid/test-config-docker.git"}}}}}}'
    deploy:
      resources:
        limits:
          memory: 500M 
        reservations:
          memory: 200M
      restart_policy:
        condition: on-failure
        max_attempts: 100

  mysql-pet:
    hostname: mysql-pet
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=c7o2r1e4
      - MYSQL_DATABASE=pet
      - MYSQL_USER=coredroid
      - MYSQL_PASSWORD=c7o2r1e4
    ports:
      - "3306:3306"
    networks:
      - spring-cloud-network

  mysql-user:
    hostname: mysql-user
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=c7o2r1e4
      - MYSQL_DATABASE=pet
      - MYSQL_USER=coredroid
      - MYSQL_PASSWORD=c7o2r1e4
    ports:
      - "3307:3306"
    networks:
      - spring-cloud-network

  mysql-record:
    hostname: mysql-record
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=c7o2r1e4
      - MYSQL_DATABASE=pet
      - MYSQL_USER=coredroid
      - MYSQL_PASSWORD=c7o2r1e4
    ports:
      - "3308:3306"
    networks:
      - spring-cloud-network

  mysql-location:
    hostname: mysql-location
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=c7o2r1e4
      - MYSQL_DATABASE=pet
      - MYSQL_USER=coredroid
      - MYSQL_PASSWORD=c7o2r1e4
    ports:
      - "3309:3306"
    networks:
      - spring-cloud-network
      
  mysql-rule:
    hostname: mysql-rule
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=c7o2r1e4
      - MYSQL_DATABASE=pet
      - MYSQL_USER=coredroid
      - MYSQL_PASSWORD=c7o2r1e4
    ports:
      - "3310:3306"
    networks:
      - spring-cloud-network

  discovery-service:
    hostname: discovery-service
    image: macoredroid/discovery-service:latest
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "30752:30752"
    networks:
      - spring-cloud-network
    deploy:
      resources:
        limits:
          memory: 500M 
        reservations:
          memory: 200M
      restart_policy:
        condition: on-failure
        max_attempts: 100
  
  pet-service:
    hostname: pet-service
    image: macoredroid/pet-service:latest
    depends_on:
      - mysql-pet
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    networks:
      - spring-cloud-network
    deploy:
      resources:
        limits:
          memory: 500M 
        reservations:
          memory: 200M
      restart_policy:
        condition: on-failure
        max_attempts: 100

  user-service:
    hostname: user-service
    image: macoredroid/user-service:latest
    depends_on:
      - mysql-user
      - mongo-cover
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    networks:
      - spring-cloud-network
    deploy:
      resources:
        limits:
          memory: 500M 
        reservations:
          memory: 200M
      restart_policy:
        condition: on-failure
        max_attempts: 100

  record-service:
    hostname: record-service
    image: macoredroid/record-service:latest
    depends_on:
      - mysql-record
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    networks:
      - spring-cloud-network
    deploy:
      resources:
        limits:
          memory: 500M 
        reservations:
          memory: 200M
      restart_policy:
        condition: on-failure
        max_attempts: 100

  location-service:
    hostname: location-service
    image: macoredroid/location-service:latest
    depends_on:
      - mysql-location
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    networks:
      - spring-cloud-network
    deploy:
      resources:
        limits:
          memory: 500M 
        reservations:
          memory: 200M
      restart_policy:
        condition: on-failure
        max_attempts: 100
      
  proxy-service:
    hostname: proxy-service
    image: macoredroid/proxy-service:latest
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "30751:30751"
    networks:
      - spring-cloud-network
    deploy:
      resources:
        limits:
          memory: 900M 
        reservations:
          memory: 200M
      restart_policy:
        condition: on-failure
        max_attempts: 100
      
  rule-service:
    hostname: rule-service
    image: macoredroid/rule-service:latest
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    depends_on:
      - mysql-rule
    networks:
      - spring-cloud-network
    deploy:
      resources:
        limits:
          memory: 500M 
        reservations:
          memory: 200M
      restart_policy:
        condition: on-failure
        max_attempts: 100
      
  mongo-moment:
    hostname: mongo-moment
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - spring-cloud-network
      
  mongo-cover:
    hostname: mongo-cover
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - spring-cloud-network
  
  mongo-auth:
    hostname: mongo-auth
    image: mongo
    ports:
      - "27019:27017"
    networks:
      - spring-cloud-network
    
  
  forum-service:
    image: macoredroid/forum-service:latest
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    networks:
      - spring-cloud-network 
    deploy:
      resources:
        limits:
          memory: 500M 
        reservations:
          memory: 200M
      restart_policy:
        condition: on-failure
        max_attempts: 100

    
networks:
  spring-cloud-network:
    driver: bridge

        
 
