version: "3.7"
services:
  config-service:
    hostname: config-service
    image: macoredroid/config-service:1.0
    ports:
      - "8088:8088"
    networks:
      - spring-cloud-network
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"server": {"git" :{"uri": "https://github.com/MaCoredroid/test-config-docker.git"}}}}}}'

  mysql-pet:
    hostname: mysql-pet
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=c7o2r1e4
      - MYSQL_DATABASE=pet
      - MYSQL_USER=coredroid
      - MYSQL_PASSWORD=c7o2r1e4
    volumes:
      - /data/mysql/pet
    ports:
      - "3306:3306"
    networks:
      - spring-cloud-network

  mysql-user:
    hostname: mysql-user
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=c7o2r1e4
      - MYSQL_DATABASE=pet
      - MYSQL_USER=coredroid
      - MYSQL_PASSWORD=c7o2r1e4
    volumes:
      - /data/mysql/user
    ports:
      - "3307:3306"
    networks:
      - spring-cloud-network

  mysql-record:
    hostname: mysql-record
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=c7o2r1e4
      - MYSQL_DATABASE=pet
      - MYSQL_USER=coredroid
      - MYSQL_PASSWORD=c7o2r1e4
    volumes:
      - /data/mysql/record
    ports:
      - "3308:3306"
    networks:
      - spring-cloud-network

  discovery-service:
    hostname: discovery-service:1.0
    image: macoredroid/discovery-service
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8061:8061"
    networks:
      - spring-cloud-network
  
  pet-service:
    hostname: pet-service:1.0
    image: macoredroid/pet-service
    depends_on:
      - mysql-pet
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8091:8091"
    networks:
      - spring-cloud-network

  user-service:
    hostname: user-service:1.0
    image: macoredroid/user-service
    depends_on:
      - mysql-user
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8092:8092"
    networks:
      - spring-cloud-network

  record-service:
    hostname: record-service:1.0
    image: macoredroid/record-service
    depends_on:
      - mysql-record
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8093:8093"
    networks:
      - spring-cloud-network

  gateway-service:
    hostname: gateway-service:1.0
    image: macoredroid/gateway-service
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8060:8060"
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge

        
 
