version: "3.7"
services:
  config-service:
    hostname: config-service
    image: macoredroid/config-service:latest
    ports:
      - "8088:8088"
    networks:
      - spring-cloud-network
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"server": {"git" :{"uri": "https://github.com/MaCoredroid/test-config-docker.git"}}}}}}'

  mysql-pet:
    hostname: mysql-pet
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=c7o2r1e4
      - MYSQL_DATABASE=pet
      - MYSQL_USER=coredroid
      - MYSQL_PASSWORD=c7o2r1e4
    ports:
      - "3306:3306"
    networks:
      - spring-cloud-network

  mysql-user:
    hostname: mysql-user
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=c7o2r1e4
      - MYSQL_DATABASE=pet
      - MYSQL_USER=coredroid
      - MYSQL_PASSWORD=c7o2r1e4
    ports:
      - "3307:3306"
    networks:
      - spring-cloud-network

  mysql-record:
    hostname: mysql-record
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=c7o2r1e4
      - MYSQL_DATABASE=pet
      - MYSQL_USER=coredroid
      - MYSQL_PASSWORD=c7o2r1e4
    ports:
      - "3308:3306"
    networks:
      - spring-cloud-network

  mysql-location:
    hostname: mysql-location
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=c7o2r1e4
      - MYSQL_DATABASE=pet
      - MYSQL_USER=coredroid
      - MYSQL_PASSWORD=c7o2r1e4
    ports:
      - "3309:3306"
    networks:
      - spring-cloud-network
      
  mysql-rule:
    hostname: mysql-rule
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=c7o2r1e4
      - MYSQL_DATABASE=pet
      - MYSQL_USER=coredroid
      - MYSQL_PASSWORD=c7o2r1e4
    ports:
      - "3310:3306"
    networks:
      - spring-cloud-network

  discovery-service:
    hostname: discovery-service
    image: macoredroid/discovery-service:latest
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "30752:30752"
    networks:
      - spring-cloud-network
  
  pet-service:
    hostname: pet-service
    image: macoredroid/pet-service:latest
    depends_on:
      - mysql-pet
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8091:8091"
    networks:
      - spring-cloud-network

  user-service:
    hostname: user-service
    image: macoredroid/user-service:latest
    depends_on:
      - mysql-user
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8092:8092"
    networks:
      - spring-cloud-network

  record-service:
    hostname: record-service
    image: macoredroid/record-service:latest
    depends_on:
      - mysql-record
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8093:8093"
    networks:
      - spring-cloud-network

  location-service:
    hostname: location-service
    image: macoredroid/location-service:latest
    depends_on:
      - mysql-record
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "8094:8094"
    networks:
      - spring-cloud-network

  gateway-service:
    hostname: gateway-service
    image: macoredroid/gateway-service:latest
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "30751:30751"
    networks:
      - spring-cloud-network
      
  proxy-service:
    hostname: proxy-service
    image: macoredroid/proxy-service:latest
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    ports:
      - "30753:30753"
    networks:
      - spring-cloud-network
      
  rule-service:
    hostname: rule-service
    image: macoredroid/rule-service:latest
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-service:8088"}}}}'
    depends_on:
      - mysql-rule
    ports:
      - "8095:8095"
    networks:
      - spring-cloud-network
      
  admin-ui:
    hostname: admin-ui
    image: macoredroid/admin-ui:latest
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network
    command: sh -c "npm start"
    environment:
      HOST: 0.0.0.0

networks:
  spring-cloud-network:
    driver: bridge

        
 
